"""Meeting organizer

Revision ID: b4041558137f
Revises: c7d7ebcc35f8
Create Date: 2025-08-28 13:51:40.770636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4041558137f'
down_revision: Union[str, None] = 'c7d7ebcc35f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('organizer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meetings', 'users', ['organizer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'organizer_id')
    # ### end Alembic commands ###
